API_KEY = "AIzaSyDKvs5bqxNxrKYKM5AG5LCrPKY3YlUsTLs"
EMAIL = "madaboutsportsuserspace@gmail.com"
PASSKEY = "@UserSpaceMAS2024"
MONGO_API = "mongodb+srv://test:test@cluster0.ezcug4b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"